### ISSUE TITLE
AUC score not consistent with sklearn implementation

### ISSUE THREAD

**Issue by Xieyangxinyu** [iarai/science4cast#4]
I was checking the `calculate_ROC` function in the tutorial against `sklearn.metrics.roc_auc_score` and they do not seem to produce the same value. Could you please take a look at this?

Thank you!

**Comment by MarioKrenn6240** [comment]
Dear @Xieyangxinyu 
Thanks a lot for your interest. I made a short script to show how to use both implementations, and how they give actually the same result:

```
import numpy as np
from sklearn.metrics import roc_auc_score
import random

from utils import calculate_ROC # from the Science4Cast competition files


y_true = [random.randint(0, 1) for _ in range(50)]
y_scores = np.random.rand(len(y_true))
print('y_true: ',y_true)
print('y_scores: ',y_scores)

sklearn_AUC=roc_auc_score(y_true, y_scores)
print('roc_auc_score: ', sklearn_AUC)


y_sorted = np.flip(np.argsort(y_scores,axis=0)) # Here we get the sorted indices from y_scores, which is the difference in implementation
science4cast_AUC=calculate_ROC(y_sorted,y_true)
print('calculate_ROC: ',science4cast_AUC)

diff_AUC=sklearn_AUC-science4cast_AUC

print('Difference between sklearn and science4cast AUC: ', diff_AUC)
```

Here, `diff_AUC` is zero (up to rounding errors at `1e-15`). The only difference is that `roc_auc_score` takes `y_true` and `y_score`, while our implementation takes the sorted index array. Therefore, please feel free to use `roc_auc_score` if you feel more comfortable with it, just keep in mind to submit the sorted index array (i.e. applying the one line i marked above).

All the best!
Mario

**Comment by Xieyangxinyu** [comment]
Hi Mario, thank you very much! I have a more pathological example here: 
```
import numpy as np
from sklearn.metrics import roc_auc_score
import random

from utils import calculate_ROC # from the Science4Cast competition files


y_true = [random.randint(0, 1) for _ in range(50)]
y_scores = [0.8 for _ in range(50)]
print('y_true: ',y_true)
print('y_scores: ',y_scores)

sklearn_AUC=roc_auc_score(y_true, y_scores)
print('roc_auc_score: ', sklearn_AUC)


y_sorted = np.flip(np.argsort(y_scores,axis=0)) # Here we get the sorted indices from y_scores, which is the difference in implementation
science4cast_AUC=calculate_ROC(y_sorted,y_true)
print('calculate_ROC: ',science4cast_AUC)

diff_AUC=sklearn_AUC-science4cast_AUC

print('Difference between sklearn and science4cast AUC: ', diff_AUC)
```

As for output, I observed that `science4cast_AUC` is different at each run while `sklearn_AUC` consistently outputs 0.5. The difference can go as large as `0.23` in my simulations.

Could you please take another look at this?

**Comment by MarioKrenn6240** [comment]
Dear @Xieyangxinyu,
Thank you for this example - I agree that in your example, there is a difference. The reason is that `sklearn_AUC` appears to average over all possibilities (which is nice!). However, for large lists, the difference vanishes. And importantly, in the competition we do have `10^6` items to predict.

I made a simple computation, how the difference scales with the number of item:

- 10^3 items:  difference= 0.00048066399569392633 +- 0.018764648344829188
- 10^4 items:  difference= 0.00035192481512291295 +- 0.0057819830552502255
- 10^5 items:  difference= 2.6299836298758245e-05 +- 0.0019147888799413602
- **10^6 items:  difference= -3.161475987013745e-05 +- 0.000569897617702283**

You see, for a list of 10^6, the difference is just `6*10^-4`

Now, here I assumed that 100% of the list has the same values. What if only a smaller part has the same values?



### For 50% same values
- 10^3 items:   difference= 0.000408321016469233 +- 0.007254382848483356
- 10^4 items:   difference= 0.0001223143660173609 +- 0.0019508968215974397
- 10^5 items:   difference= -0.00012165713290714974 +- 0.0006291909178979867
- **10^6 items:   difference= -4.5152062509025094e-05 +- 0.00020330611937285453**

The difference decreases further.

### For 20% same values
- 10^3 items:   difference= 0.00011188218596605848 +- 0.0016122433804812198
- 10^4 items:   difference= -3.8159323982939196e-05 +- 0.0005023650438388073
- 10^5 items:   difference= 6.444445111430385e-06 +- 0.00016076891116120878
- **10^6 items:   difference= -1.1565070675205524e-05 +- 4.514607511739168e-05**

Consequently, the difference between our `calculate_ROC` and `sklearn_AUC` is neglectable for the competition evaluation set.

That means, you can chose between them freely, if one of them is faster or you can use them in some end-to-end training.

Thanks a lot for your comment again, and let me know if i can help any further!
Mario

**Comment by Xieyangxinyu** [comment]
Thank you Mario! This is very helpful! 👍
